import { alternarMenu } from './menu.js';

const ROTAS = new Set(['index.html', 'projetos.html', 'sobre.html', 'cadastro.html', 'termos.html']);
let requisicaoAtual;

function nomeDoArquivo(pathname) { const ultimo = pathname.split('/').filter(Boolean).at(-1) || 'index.html'; return ultimo.includes('.') ? ultimo : 'index.html'; }
function rotaInterna(link) { if (!link) return null; const href = link.getAttribute('href'); if (!href || href.startsWith('#') || link.hasAttribute('download') || (link.target && link.target.toLowerCase() !== '_self')) return null; let destino; try { destino = new URL(link.href, location.href); } catch { return null; } return destino.origin === location.origin && ROTAS.has(nomeDoArquivo(destino.pathname)) && !(destino.pathname === location.pathname && destino.search === location.search && destino.hash) ? destino : null; }
function focarPrincipal() { const titulo = document.querySelector('#app h1, main h1'); if (!titulo) return; titulo.setAttribute('tabindex', '-1'); titulo.focus({ preventScroll: true }); titulo.addEventListener('blur', () => titulo.removeAttribute('tabindex'), { once: true }); }

export function atualizarNavegacaoAtiva(url) { const atual = nomeDoArquivo(url.pathname); document.querySelectorAll('.nav-list a').forEach((link) => { const ativo = nomeDoArquivo(new URL(link.href, location.href).pathname) === atual; if (ativo) link.setAttribute('aria-current', 'page'); else link.removeAttribute('aria-current'); }); }
export function iniciarRouter({ iniciarTela, limparTela, obterFormulario }) {
  const renderizar = async (destino, atualizarHistorico = true) => { const atual = document.querySelector('#app'); if (!atual) return; alternarMenu(false); requisicaoAtual?.abort(); requisicaoAtual = new AbortController(); atual.setAttribute('aria-busy', 'true'); try { const resposta = await fetch(destino.href, { headers: { 'X-Requested-With': 'PonteDigitalSPA' }, signal: requisicaoAtual.signal }); if (!resposta.ok) throw new Error(`Falha HTTP ${resposta.status}`); const documento = new DOMParser().parseFromString(await resposta.text(), 'text/html'); const proximo = documento.querySelector('#app'); if (!proximo) throw new Error('A rota não possui o container principal #app.'); limparTela(); atual.replaceWith(document.importNode(proximo, true)); document.title = documento.title || 'Ponte Digital'; if (atualizarHistorico) history.pushState({ rota: destino.pathname }, '', `${destino.pathname}${destino.search}${destino.hash}`); atualizarNavegacaoAtiva(destino); iniciarTela(); scrollTo({ top: 0, left: 0, behavior: 'auto' }); requestAnimationFrame(focarPrincipal); } catch (erro) { if (erro.name !== 'AbortError') { console.error('Não foi possível renderizar a rota pela SPA.', erro); location.assign(destino.href); } } finally { document.querySelector('#app')?.removeAttribute('aria-busy'); } };
  document.addEventListener('click', (event) => { if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; const destino = rotaInterna(event.target.closest('a[href]')); if (!destino) return; event.preventDefault(); if (destino.href === location.href) { alternarMenu(false); scrollTo({ top: 0, left: 0, behavior: 'auto' }); focarPrincipal(); } else renderizar(destino); });
  addEventListener('popstate', () => renderizar(new URL(location.href), false));
  document.addEventListener('keydown', (event) => { const controle = obterFormulario(); const modal = controle?.modal; if (event.key === 'Escape') { if (modal && !modal.hidden) controle.fecharModal(); if (document.querySelector('.menu-toggle')?.getAttribute('aria-expanded') === 'true') alternarMenu(false); return; } if (event.key !== 'Tab' || !modal || modal.hidden) return; const itens = [...modal.querySelectorAll('button:not([disabled])')]; const primeiro = itens[0]; const ultimo = itens.at(-1); if (event.shiftKey && document.activeElement === primeiro) { event.preventDefault(); ultimo?.focus(); } else if (!event.shiftKey && document.activeElement === ultimo) { event.preventDefault(); primeiro?.focus(); } });
  history.replaceState({ rota: location.pathname }, '', location.href);
}
